#!/usr/bin/env bash
# compile-gpugemv-shader.sh — AOT-compile Q4_K GEMV shaders to C headers.
#
# Compiles:
#   shaders/gpugemv_q4k.hlsl        → gpugemv_q4k_dxil.h        (naive, H6.1)
#   shaders/gpugemv_q4k_wave32.hlsl → gpugemv_q4k_wave32_dxil.h (H6.2 LDS-red)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DXC="${DXC:-dxc}"

if [[ ! -x "$DXC" ]] && ! command -v "$DXC" >/dev/null 2>&1; then
	echo "dxc not found (set DXC=...). Example Linux release:" >&2
	echo "  https://github.com/microsoft/DirectXShaderCompiler/releases" >&2
	echo "  pacman extra/directx-shader-compiler (do not install AUR packages)" >&2
	exit 1
fi

emit_header() {
	local dxil="$1"
	local out_h="$2"
	local source_rel="$3"
	local symbol="$4"
	python3 - "$dxil" "$out_h" "$source_rel" "$symbol" <<'PY'
import sys
from pathlib import Path

data = Path(sys.argv[1]).read_bytes()
out = Path(sys.argv[2])
source = sys.argv[3]
symbol = sys.argv[4]
out.parent.mkdir(parents=True, exist_ok=True)
lines = [
    "// AUTO-GENERATED by scripts/compile-gpugemv-shader.sh — do not edit.",
    f"// Source: {source} (cs_6_0 CSMain)",
    "#pragma once",
    "#include <cstddef>",
    "#include <cstdint>",
    f"// {len(data)} bytes DXIL",
    "// clang-format off",
    f"static const uint8_t {symbol}[] = {{",
]
for i in range(0, len(data), 12):
    chunk = data[i : i + 12]
    lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
lines.append("};")
lines.append(f"static const size_t {symbol}Size = {len(data)};")
lines.append("// clang-format on")
out.write_text("\n".join(lines) + "\n")
print(f"wrote {out} ({len(data)} bytes)")
PY
}

compile_one() {
	local hlsl="$1"
	local out_h="$2"
	local source_rel="$3"
	local symbol="$4"
	local tmp
	tmp="$(mktemp)"
	"$DXC" -T cs_6_0 -E CSMain -Fo "$tmp" "$hlsl"
	emit_header "$tmp" "$out_h" "$source_rel" "$symbol"
	rm -f "$tmp"
}

compile_one "$ROOT/shaders/gpugemv_q4k.hlsl" \
	"$ROOT/shaders/generated/gpugemv_q4k_dxil.h" \
	"shaders/gpugemv_q4k.hlsl" \
	"kGpugemvQ4kDxil"

compile_one "$ROOT/shaders/gpugemv_q4k_wave32.hlsl" \
	"$ROOT/shaders/generated/gpugemv_q4k_wave32_dxil.h" \
	"shaders/gpugemv_q4k_wave32.hlsl" \
	"kGpugemvQ4kWave32Dxil"
