#!/usr/bin/env bash
# compile-gpubw-shader.sh — AOT-compile shaders/gpubw_stream.hlsl to a C header.
#
# Requires dxc (DirectXShaderCompiler). Regenerates
# shaders/generated/gpubw_stream_dxil.h for embedding in gpubw.cpp.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HLSL="$ROOT/shaders/gpubw_stream.hlsl"
OUT_H="$ROOT/shaders/generated/gpubw_stream_dxil.h"
DXC="${DXC:-dxc}"

if ! command -v "$DXC" >/dev/null 2>&1; then
	echo "dxc not on PATH (set DXC=...). Example Linux release:" >&2
	echo "  https://github.com/microsoft/DirectXShaderCompiler/releases" >&2
	exit 1
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
"$DXC" -T cs_6_0 -E CSMain -Fo "$tmp" "$HLSL"
python3 - "$tmp" "$OUT_H" <<'PY'
import sys
from pathlib import Path
data = Path(sys.argv[1]).read_bytes()
out = Path(sys.argv[2])
out.parent.mkdir(parents=True, exist_ok=True)
lines = [
    "// AUTO-GENERATED by scripts/compile-gpubw-shader.sh — do not edit.",
    "// Source: shaders/gpubw_stream.hlsl (cs_6_0 CSMain)",
    "#pragma once",
    "#include <cstddef>",
    "#include <cstdint>",
    f"// {len(data)} bytes DXIL",
    "static const uint8_t kGpubwStreamDxil[] = {",
]
for i in range(0, len(data), 12):
    chunk = data[i : i + 12]
    lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
lines.append("};")
lines.append(f"static const size_t kGpubwStreamDxilSize = {len(data)};")
out.write_text("\n".join(lines) + "\n")
print(f"wrote {out} ({len(data)} bytes)")
PY
