#!/usr/bin/env bash
# compile-gpugemv-shader.sh — AOT-compile shaders/gpugemv_q4k.hlsl to a C header.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HLSL="$ROOT/shaders/gpugemv_q4k.hlsl"
OUT_H="$ROOT/shaders/generated/gpugemv_q4k_dxil.h"
DXC="${DXC:-dxc}"

if [[ ! -x "$DXC" ]] && ! command -v "$DXC" >/dev/null 2>&1; then
	echo "dxc not found (set DXC=...). Example Linux release:" >&2
	echo "  https://github.com/microsoft/DirectXShaderCompiler/releases" >&2
	exit 1
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
"$DXC" -T cs_6_0 -E CSMain -Fo "$tmp" "$HLSL"
python3 - "$tmp" "$OUT_H" <<'PY'
import sys
from pathlib import Path

data = Path(sys.argv[1]).read_bytes()
out = Path(sys.argv[2])
out.parent.mkdir(parents=True, exist_ok=True)
lines = [
    "// AUTO-GENERATED by scripts/compile-gpugemv-shader.sh — do not edit.",
    "// Source: shaders/gpugemv_q4k.hlsl (cs_6_0 CSMain)",
    "#pragma once",
    "#include <cstddef>",
    "#include <cstdint>",
    f"// {len(data)} bytes DXIL",
    "// clang-format off",
    "static const uint8_t kGpugemvQ4kDxil[] = {",
]
for i in range(0, len(data), 12):
    chunk = data[i : i + 12]
    lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
lines.append("};")
lines.append(f"static const size_t kGpugemvQ4kDxilSize = {len(data)};")
lines.append("// clang-format on")
out.write_text("\n".join(lines) + "\n")
print(f"wrote {out} ({len(data)} bytes)")
PY
