// Copyright (c) 2024 Venere Labs
// SPDX-License-Identifier: MIT

#ifdef XLLAMA_UWP

// clang-format off
// pch.h must be first: it includes <unknwn.h> before WinRT headers (COM IUnknown guard).
// SortIncludes would move it after MainPage.h alphabetically, breaking the C2338 check.
#include "pch.h"
#include "MainPage.h"
// Declarations generated by MarkupCompilePass1 (template MainPageT with named
// element accessors like OutputText(), RunButton(), etc. and their backing members).
#include "MainPage.xaml.g.h"
// clang-format on

// MarkupCompilePass2 is disabled (WMC9999 crash). Provide template definitions
// so MSVC can emit the vtable adjustor thunks it needs for the COM vtable layout.
// Virtual dispatch through MainPage* still calls MainPage::Connect (most-derived).
namespace winrt::xllama::implementation {

template <typename D, typename... I>
void MainPageT<D, I...>::Connect(int32_t, ::winrt::Windows::Foundation::IInspectable const&) {}

template <typename D, typename... I>
::winrt::Windows::UI::Xaml::Markup::IComponentConnector
MainPageT<D, I...>::GetBindingConnector(int32_t,
                                        ::winrt::Windows::Foundation::IInspectable const&) {
    return nullptr;
}

// Explicit instantiation inside the namespace avoids MSVC C3083 with qualified names.
template void MainPageT<MainPage>::Connect(int32_t,
                                           ::winrt::Windows::Foundation::IInspectable const&);
template ::winrt::Windows::UI::Xaml::Markup::IComponentConnector
MainPageT<MainPage>::GetBindingConnector(int32_t,
                                         ::winrt::Windows::Foundation::IInspectable const&);

} // namespace winrt::xllama::implementation

    #include "xllama/utf8_utils.h"

    #include <cstdio>
    #include <string>
    #include <thread>

using namespace winrt;
using namespace winrt::Windows::Foundation;
using namespace winrt::Windows::Storage;
using namespace winrt::Windows::UI::Core;
using namespace winrt::Windows::UI::Xaml;
using namespace winrt::Windows::UI::Xaml::Controls;

namespace winrt::xllama::implementation {

// Wide LocalFolder path: ApplicationData::LocalFolder\<filename_w>
// (path_utils returns UTF-8; _wfopen needs wstring — kept local to avoid
// polluting the cross-platform path_utils API with a UTF-16-only variant)
static std::wstring local_wpath(const wchar_t* filename_w) {
    auto folder = ApplicationData::Current().LocalFolder();
    return std::wstring(folder.Path().c_str()) + L"\\" + filename_w;
}

static void page_log(const char* msg) {
    OutputDebugStringA(msg);
    try {
        auto path = local_wpath(L"xllama.log");
        FILE* f = _wfopen(path.c_str(), L"a");
        if (f) {
            fputs(msg, f);
            fclose(f);
        }
    } catch (...) {
    }
}

// ---------------------------------------------------------------------------
// XAML-generated method implementations (normally produced by MarkupCompilePass2;
// provided manually because XamlC.exe crashes WMC9999 for C++/WinRT projects).
// ---------------------------------------------------------------------------

void MainPage::InitializeComponent() {
    // Parse MainPage.xaml at runtime (text XAML, no XBF — ~10 ms overhead on
    // first launch, acceptable on Xbox). LoadComponent calls Connect() for each
    // named element so the backing members get populated.
    using ComponentResourceLocation =
        ::winrt::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation;
    page_log("[xllama] MainPage::InitializeComponent: loading MainPage.xaml\n");
    try {
        ::winrt::Windows::UI::Xaml::Application::LoadComponent(
            *this, ::winrt::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml"),
            ComponentResourceLocation::Application);
        page_log("[xllama] MainPage::InitializeComponent: done\n");
    } catch (winrt::hresult_error const& e) {
        char buf[512];
        snprintf(buf, sizeof(buf), "[xllama] MainPage::InitializeComponent FAILED 0x%08X: %ls\n",
                 static_cast<unsigned>(e.code().value), e.message().c_str());
        page_log(buf);
        throw;
    }
}

void MainPage::Connect(int32_t connectionId,
                       ::winrt::Windows::Foundation::IInspectable const& target) {
    // Connection IDs are assigned by the XAML compiler in document order of
    // x:Name attributes (depth-first traversal of the XAML tree, 1-based).
    // Order in MainPage.xaml: ModelText(1) StatusText(2) LoadingBar(3)
    //   OutputScroll(4) PromptInput(5) OutputText(6) MetricsText(7)
    //   RunButton(8) CancelButton(9).
    switch (connectionId) {
    case 1:
        ModelText(target.as<::winrt::Windows::UI::Xaml::Controls::TextBlock>());
        break;
    case 2:
        StatusText(target.as<::winrt::Windows::UI::Xaml::Controls::TextBlock>());
        break;
    case 3:
        LoadingBar(target.as<::winrt::Windows::UI::Xaml::Controls::ProgressBar>());
        break;
    case 4:
        OutputScroll(target.as<::winrt::Windows::UI::Xaml::Controls::ScrollViewer>());
        break;
    case 5:
        PromptInput(target.as<::winrt::Windows::UI::Xaml::Controls::TextBox>());
        break;
    case 6:
        OutputText(target.as<::winrt::Windows::UI::Xaml::Controls::TextBlock>());
        break;
    case 7:
        MetricsText(target.as<::winrt::Windows::UI::Xaml::Controls::TextBlock>());
        break;
    case 8:
        RunButton(target.as<::winrt::Windows::UI::Xaml::Controls::Button>());
        break;
    case 9:
        CancelButton(target.as<::winrt::Windows::UI::Xaml::Controls::Button>());
        break;
    }
}

::winrt::Windows::UI::Xaml::Markup::IComponentConnector
MainPage::GetBindingConnector(int32_t, ::winrt::Windows::Foundation::IInspectable const&) {
    return nullptr; // no x:Bind in this page
}

// ---------------------------------------------------------------------------
// Constructor
// ---------------------------------------------------------------------------

MainPage::MainPage() {
    InitializeComponent();
    RunButton().Click({this, &MainPage::OnRunClick});
    CancelButton().Click({this, &MainPage::OnCancelClick});
    LoadModelName();
    CheckBenchMode();
}

// ---------------------------------------------------------------------------
// UI helpers (must be called on UI thread)
// ---------------------------------------------------------------------------

void MainPage::AppendOutput(std::wstring const& text) {
    OutputText().Text(OutputText().Text() + text);
    // Auto-scroll to bottom
    OutputScroll().UpdateLayout();
    OutputScroll().ChangeView(nullptr, OutputScroll().ScrollableHeight(), nullptr);
}

void MainPage::SetStatus(std::wstring const& status) {
    StatusText().Text(status);
}

void MainPage::SetRunning(bool running) {
    RunButton().IsEnabled(!running);
    CancelButton().IsEnabled(running);
    LoadingBar().Visibility(running ? Visibility::Visible : Visibility::Collapsed);
}

// ---------------------------------------------------------------------------
// LoadModelName: read model.txt from LocalFolder
// ---------------------------------------------------------------------------

void MainPage::LoadModelName() {
    auto path = local_wpath(L"model.txt");
    FILE* f = _wfopen(path.c_str(), L"r");
    if (f) {
        wchar_t buf[512] = {};
        if (fgetws(buf, 511, f)) {
            // trim trailing whitespace
            size_t len = wcslen(buf);
            while (len > 0 &&
                   (buf[len - 1] == L'\n' || buf[len - 1] == L'\r' || buf[len - 1] == L' '))
                buf[--len] = L'\0';
            m_model_filename = buf;
        }
        fclose(f);
    }
    if (m_model_filename.empty())
        m_model_filename = L"Qwen_Qwen3-1.7B-Q4_K_M.gguf";

    ModelText().Text(m_model_filename);
}

// ---------------------------------------------------------------------------
// CheckBenchMode: detect bench.flag and auto-run main_loop if present
// ---------------------------------------------------------------------------

fire_and_forget MainPage::CheckBenchMode() {
    auto self = get_strong();

    co_await resume_background();

    auto flag_path = local_wpath(L"bench.flag");
    FILE* f = _wfopen(flag_path.c_str(), L"r");
    if (!f)
        co_return;
    fclose(f);

    // Bench mode detected — update UI and run main_loop
    co_await resume_foreground(self->Dispatcher());
    self->SetStatus(L"Bench mode — running...");
    self->SetRunning(true);
    self->RunButton().IsEnabled(false);

    co_await resume_background();
    ::xllama::bridge::main_loop();

    co_await resume_foreground(self->Dispatcher());
    self->SetStatus(L"Bench complete");
    self->SetRunning(false);
}

// ---------------------------------------------------------------------------
// StartInference: called on UI thread; spawns background thread
// ---------------------------------------------------------------------------

void MainPage::StartInference(std::wstring const& prompt_w) {
    m_abort.store(false);
    SetStatus(L"Loading model...");
    SetRunning(true);
    OutputText().Text(L"");
    MetricsText().Text(L"");

    auto self = get_strong();
    std::string prompt = ::xllama::wstring_to_utf8(prompt_w);
    std::string model = ::xllama::wstring_to_utf8(m_model_filename);

    std::thread([self, prompt, model]() {
        ::xllama::bridge::InferenceParams params;
        params.model_path = model;
        params.prompt = prompt;
        params.n_predict = 512;
        params.abort_flag = &self->m_abort;

        auto dispatcher = self->Dispatcher();

        params.on_status = [self, dispatcher](const std::string& s) {
            auto ws = ::xllama::utf8_to_wstring(s);
            dispatcher.RunAsync(CoreDispatcherPriority::Normal,
                                [self, ws]() { self->SetStatus(ws); });
        };

        params.on_token = [self, dispatcher](const std::string& tok) {
            auto wtok = ::xllama::utf8_to_wstring(tok);
            dispatcher.RunAsync(CoreDispatcherPriority::Normal,
                                [self, wtok]() { self->AppendOutput(wtok); });
        };

        auto res = ::xllama::bridge::run_inference(params);

        // Format metrics
        std::wstring metrics;
        if (res.success) {
            wchar_t buf[256];
            double pt = (res.n_p_eval > 0 && res.t_p_eval_ms > 0)
                            ? (double)res.n_p_eval / (res.t_p_eval_ms / 1000.0)
                            : 0.0;
            double dt = (res.n_eval > 0 && res.t_eval_ms > 0)
                            ? (double)res.n_eval / (res.t_eval_ms / 1000.0)
                            : 0.0;
            swprintf_s(buf, L"prompt %.1f tok/s  ·  decode %.1f tok/s  ·  peak %zu MB", pt, dt,
                       res.peak_ws_mb);
            metrics = buf;
        } else {
            metrics = ::xllama::utf8_to_wstring(res.error_msg.empty() ? "inference failed"
                                                                      : res.error_msg);
        }

        dispatcher.RunAsync(CoreDispatcherPriority::Normal, [self, metrics, res]() {
            self->MetricsText().Text(metrics);
            self->SetStatus(res.success ? L"Done" : L"Error");
            self->SetRunning(false);
        });
    }).detach();
}

// ---------------------------------------------------------------------------
// Event handlers
// ---------------------------------------------------------------------------

void MainPage::OnRunClick(IInspectable const&, RoutedEventArgs const&) {
    auto prompt = PromptInput().Text();
    if (prompt.empty()) {
        SetStatus(L"Enter a prompt first");
        return;
    }
    StartInference(std::wstring(prompt.c_str()));
}

void MainPage::OnCancelClick(IInspectable const&, RoutedEventArgs const&) {
    m_abort.store(true);
    SetStatus(L"Cancelling...");
    CancelButton().IsEnabled(false);
}

} // namespace winrt::xllama::implementation

#endif // XLLAMA_UWP
