#pragma once

#ifdef XLLAMA_UWP

#include "pch.h"
#include "MainPage.g.h"
#include "llama-bridge.h"

#include <atomic>
#include <string>
#include <thread>

namespace winrt::xllama::implementation {

struct MainPage : MainPageT<MainPage> {
    MainPage();

    // Normally generated by MarkupCompilePass2; provided manually because the
    // XAML compiler crashes (WMC9999) for C++/WinRT projects in both SDK
    // 22621 and 26100. See MainPage.cpp for implementations.
    void InitializeComponent();
    void Connect(int32_t connectionId,
                 winrt::Windows::Foundation::IInspectable const& target) override;
    winrt::Windows::UI::Xaml::Markup::IComponentConnector
        GetBindingConnector(int32_t connectionId,
                            winrt::Windows::Foundation::IInspectable const& target) override;

    void OnRunClick(winrt::Windows::Foundation::IInspectable const&,
                    winrt::Windows::UI::Xaml::RoutedEventArgs const&);
    void OnCancelClick(winrt::Windows::Foundation::IInspectable const&,
                       winrt::Windows::UI::Xaml::RoutedEventArgs const&);

private:
    std::atomic<bool>    m_abort{false};
    std::wstring         m_model_filename;

    void LoadModelName();
    winrt::fire_and_forget CheckBenchMode();
    void StartInference(std::wstring const& prompt);
    void AppendOutput(std::wstring const& text);
    void SetStatus(std::wstring const& status);
    void SetRunning(bool running);
};

} // namespace winrt::xllama::implementation

namespace winrt::xllama::factory_implementation {

struct MainPage : MainPageT<MainPage, implementation::MainPage> {};

} // namespace winrt::xllama::factory_implementation

#endif // XLLAMA_UWP
