// Copyright (c) 2024 Venere Labs
// SPDX-License-Identifier: MIT

// Compile the cppwinrt 2.0 factory aggregator generated by the NuGet.
// In cppwinrt 2.x, CppWinRTMakeComponentProjection emits a single
// module.g.cpp instead of per-class App.g.cpp / MainPage.g.cpp.
// module.g.cpp needs factory_implementation::{App,MainPage} in scope.
#ifdef XLLAMA_UWP

// clang-format off
// pch.h must be first (unknwn.h guard); module.g.cpp must be last (implementation unit).
#include "pch.h"
#include "App.h"
#include "MainPage.h"
#include "module.g.cpp"
// clang-format on

#endif // XLLAMA_UWP
