#pragma once

#ifdef XLLAMA_UWP

// <windows.h> must come before winrt headers; wWinMain uses HINSTANCE/PWSTR.
#ifndef WIN32_LEAN_AND_MEAN
#  define WIN32_LEAN_AND_MEAN
#endif
#ifndef NOMINMAX
#  define NOMINMAX
#endif
#include <windows.h>
// WIN32_LEAN_AND_MEAN omits objbase.h (which includes unknwn.h). winrt/base.h
// has a static_assert requiring IUnknown to be defined first, so include it
// explicitly before any C++/WinRT header.
#include <unknwn.h>

#include <winrt/base.h>
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.ApplicationModel.Core.h>
#include <winrt/Windows.ApplicationModel.Activation.h>
#include <winrt/Windows.UI.Core.h>
#include <winrt/Windows.UI.Xaml.h>
#include <winrt/Windows.UI.Xaml.Controls.h>
#include <winrt/Windows.UI.Xaml.Controls.Primitives.h>
#include <winrt/Windows.UI.Xaml.Navigation.h>
#include <winrt/Windows.UI.Xaml.Markup.h>
#include <winrt/Windows.UI.Xaml.Interop.h>
#include <winrt/Windows.Storage.h>
#include <winrt/Windows.Storage.Streams.h>
// WinUI 2 C++/WinRT projection headers — generated by cppwinrt.exe at build
// time from Microsoft.UI.Xaml.winmd into $(IntDir)Generated Files\winrt\.
// They are findable because $(IntDir)Generated Files is in AdditionalIncludeDirectories
// and CppWinRT.targets runs before ClCompile.
#include <winrt/Microsoft.UI.Xaml.h>
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#include <winrt/Microsoft.UI.Xaml.XamlTypeInfo.h>

#endif // XLLAMA_UWP
