// XamlLibMetadataProvider.g.cpp is generated by MarkupCompilePass1 and provides
// the implementations of XamlTypeInfoProvider::CreateXamlType, CreateXamlMember,
// OtherProviders — referenced by XamlTypeInfo.Impl.g.cpp (auto-compiled via
// GeneratedCodeFiles). This wrapper compiles it as a separate translation unit.
#ifdef XLLAMA_UWP
#include "pch.h"
#include "XamlLibMetadataProvider.g.cpp"
#endif
