# The UWP MSBuild project bypasses ggml's CMake configure step. Generate its
# version header from the upstream version declarations and template.
if(NOT DEFINED GGML_SOURCE_DIR OR NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "GGML_SOURCE_DIR and OUTPUT_FILE are required")
endif()
file(READ "${GGML_SOURCE_DIR}/CMakeLists.txt" version_source)
foreach(component MAJOR MINOR PATCH)
    string(REGEX MATCH "set\\(GGML_VERSION_${component} ([0-9]+)\\)" match "${version_source}")
    if(NOT match)
        message(FATAL_ERROR "Cannot read upstream GGML_VERSION_${component}")
    endif()
    set(GGML_VERSION_${component} "${CMAKE_MATCH_1}")
endforeach()
set(GGML_VERSION "${GGML_VERSION_MAJOR}.${GGML_VERSION_MINOR}.${GGML_VERSION_PATCH}")
get_filename_component(LLAMA_SOURCE_DIR "${GGML_SOURCE_DIR}" DIRECTORY)
file(READ "${LLAMA_SOURCE_DIR}/CMakeLists.txt" llama_version_source)
foreach(component MAJOR MINOR PATCH)
    string(REGEX MATCH "set\\(LLAMA_VERSION_${component} ([0-9]+)\\)" match "${llama_version_source}")
    if(NOT match)
        message(FATAL_ERROR "Cannot read upstream LLAMA_VERSION_${component}")
    endif()
    set(LLAMA_VERSION_${component} "${CMAKE_MATCH_1}")
endforeach()
set(LLAMA_VERSION "${LLAMA_VERSION_MAJOR}.${LLAMA_VERSION_MINOR}.${LLAMA_VERSION_PATCH}")
string(REGEX MATCH "option\\(LLAMA_BUILD_IS_DEV[^\n]* (ON|OFF)\\)" match "${llama_version_source}")
if(NOT match)
    message(FATAL_ERROR "Cannot read upstream LLAMA_BUILD_IS_DEV default")
endif()
if(CMAKE_MATCH_1 STREQUAL "ON")
    string(APPEND LLAMA_VERSION "-dev")
endif()
find_program(GIT_EXE NAMES git git.exe REQUIRED)
execute_process(COMMAND "${GIT_EXE}" rev-parse --short HEAD
    WORKING_DIRECTORY "${GGML_SOURCE_DIR}"
    OUTPUT_VARIABLE GGML_BUILD_COMMIT OUTPUT_STRIP_TRAILING_WHITESPACE
    COMMAND_ERROR_IS_FATAL ANY)
set(LLAMA_BUILD_COMMIT "${GGML_BUILD_COMMIT}")
execute_process(COMMAND "${GIT_EXE}" diff-index --quiet HEAD -- .
    WORKING_DIRECTORY "${GGML_SOURCE_DIR}" RESULT_VARIABLE dirty)
if(dirty EQUAL 1)
    string(APPEND GGML_BUILD_COMMIT "-dirty")
elseif(NOT dirty EQUAL 0)
    message(FATAL_ERROR "Cannot determine ggml working-tree identity")
endif()
configure_file("${GGML_SOURCE_DIR}/src/ggml-version.h.in" "${OUTPUT_FILE}" @ONLY)
get_filename_component(output_dir "${OUTPUT_FILE}" DIRECTORY)
configure_file("${LLAMA_SOURCE_DIR}/src/llama-version.h.in" "${output_dir}/llama-version.h" @ONLY)
